// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyChXwwK44OY-a04McuGvwBA1_rv4iyQ1js',
    appId: '1:121880356291:web:5a15122078e2b3c9810976',
    messagingSenderId: '121880356291',
    projectId: 'mtaproject-b19ed',
    authDomain: 'mtaproject-b19ed.firebaseapp.com',
    databaseURL: 'https://mtaproject-b19ed-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'mtaproject-b19ed.appspot.com',
    measurementId: 'G-ERZN0K8KGP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDm5J4dOWlZkAzMfUNzh-Iy5jY1Lfnro7U',
    appId: '1:121880356291:android:b9394f0a810364a8810976',
    messagingSenderId: '121880356291',
    projectId: 'mtaproject-b19ed',
    databaseURL: 'https://mtaproject-b19ed-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'mtaproject-b19ed.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD6Y4qbBVmxJMwQyxwaUlAgMl0O_nRhWz0',
    appId: '1:121880356291:ios:460c98cff894822a810976',
    messagingSenderId: '121880356291',
    projectId: 'mtaproject-b19ed',
    databaseURL: 'https://mtaproject-b19ed-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'mtaproject-b19ed.appspot.com',
    iosClientId: '121880356291-8188oa7tca3cv4elpilq45ue0o4m4mbi.apps.googleusercontent.com',
    iosBundleId: 'com.example.truemoneyversion2',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD6Y4qbBVmxJMwQyxwaUlAgMl0O_nRhWz0',
    appId: '1:121880356291:ios:460c98cff894822a810976',
    messagingSenderId: '121880356291',
    projectId: 'mtaproject-b19ed',
    databaseURL: 'https://mtaproject-b19ed-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'mtaproject-b19ed.appspot.com',
    iosClientId: '121880356291-8188oa7tca3cv4elpilq45ue0o4m4mbi.apps.googleusercontent.com',
    iosBundleId: 'com.example.truemoneyversion2',
  );
}
